name: 'CI'
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo '${{ github.event.action }}'
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Format
        run: 'npm run format'
      
      - name: Lint
        run: 'npm run lint'

  Test-Unit:
    name: Test - Unit
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo '${{ github.event.action }}'
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Test
        run: 'npm run test'

  Test-Action: # make sure the action works on a clean machine without building
    name: Test - Action
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          days-before-stale: 1
          days-before-delete: 200
          comment-updates: true
          max-issues: 30
          tag-committer: true
          stale-branch-label: 'stale branch üóëÔ∏è'
          compare-branches: 'info'
          branches-filter-regex: '^((?!dependabot))'


  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: [Lint, Test-Unit, Test-Action]
    steps:
      - name: Print GitHub event action
        run: |
          echo '${{ github.event.action }}'

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Build
        run: 'npm run build && npm run package'


